[package]
name = "bevy_gearbox"
version = "0.3.1"
edition = "2021"
description = "State machine system for the bevy game engine"
license = "MIT OR Apache-2.0"
repository = "https://github.com/DEMIURGE-studio/bevy_gearbox"
homepage = "https://github.com/DEMIURGE-studio/bevy_gearbox"
readme = "README.md"
keywords = ["bevy", "state-machine", "gamedev", "ecs"]
categories = ["game-development", "game-engines"]

[dependencies]
bevy = "0.16.1"
bevy_ecs = { version = "0.16.1", default-features = false }

[dev-dependencies]
bevy = { version = "0.16.1", features = ["default"] }
bevy-inspector-egui = "0.32.0"